### ISSUE TITLE
!!!!Add tests!!!!

### ISSUE THREAD

**Issue by SlaynAndKorpil** [mTvare6/hello-world.rs#12]
I know that rust(:rocket:) is a 100% safe language where no bugs could ever get past the borrow checker, but since this project due to its amazing speed :rocket: will most likely be a critical dependency for the next space missions, we should try to ensure its functionality with tests.

I would recommend a minimum of 20 unit tests which should each take at least 10 hours to run just to be sure.

**Comment by mTvare6** [comment]
You are right, our enterprise level users would want memory safety and tests

**Comment by mTvare6** [comment]
@SlaynAndKorpil implemented as of [#1d5772e](https://github.com/mTvare6/hello-world.rs/commit/1d5772eb99382b819365759b33517ac359881694)

**Comment by mTvare6** [comment]
CI is setup too, closing now
