### ISSUE TITLE
Need more dependencies

### ISSUE THREAD

**Issue by binex-dsk** [mTvare6/hello-world.rs#195]
**Is your feature request related to a problem? Please describe.**
Needs a few more dependencies. The current deps are sufficient but we need more dependencies to counteract unsafe crates. 

**Describe the solution you'd like**
Add more deps

**Additional context**

**Comment by alexislefebvre** [comment]
Are 67k crates enough? https://github.com/mTvare6/hello-world.rs/pull/184

**Comment by binex-dsk** [comment]
Yes
