### ISSUE TITLE
Compiles too fast

### ISSUE THREAD

**Issue by robertmsale** [mTvare6/hello-world.rs#209]
**Describe the bug**
Compared to the compile times I see for hello world implementations on modest languages such as C++, this cargo package just compiles too fast. I hardly have time to read the entire Stephen King's IT between the time I hit "build" and the time it finishes. This is a problem because my boss expects me to write code while it is not compiling.

**To Reproduce**
1. `cargo run`

**Expected behavior**
A reasonable compilation time of at least 3 hours or so.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 0xDEADBEEF
**Additional context**

**Comment by nothingnesses** [comment]
Have you tried running with the release profile (`cargo run --release`)? It usually has the added bonus of making the resulting binary run at least 91x faster (that's over 9000% speed), but YMMV.

**Comment by robertmsale** [comment]
That did the trick! Thank you
