### ISSUE TITLE
question: why is "unsafe" in the code base???

### ISSUE THREAD

**Issue by Gitleptune** [mTvare6/hello-world.rs#22]
I thought that rust(🚀) was very memory safe and blazing fast, but as I went through the codebase (main.rs(🚀)) I stumbled upon this piece of code that really shook me.
https://github.com/mTvare6/hello-world.rs/blob/3178620b525661514cdf65f6f32558569f566a5a/src/main.rs#L85-L105
WHY IS THE CODE "unsafe"????

I will stop using this product from now on. 😮‍💨

_This issue was written with [basedmark](https://github.com/besterestmark/bettermark)🚀_

**Comment by mTvare6** [comment]
@Gitleptune rust can tranform unsafe -> safe, poof, magic. This is why we encourage magic ecosystem to the c soydevs, and they won't accept it

**Comment by legendofmiracles** [comment]
This code is also furthermore tested verbatim in rust's own compiler and is thus guaranteed to always work

**Comment by mTvare6** [comment]
Check the recent code and their commentsq
