### ISSUE TITLE
Doesnt use GTK-4

### ISSUE THREAD

**Issue by JAicewizard** [mTvare6/hello-world.rs#228]
**Describe the bug**
This application uses the old and practically ancient crate for GTK3

**To Reproduce**
`cargo build`

**Expected behavior**
Should build an application using GTK4,

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
There are some major benefits of GTK4, namely that it was released in 2020.
There might be a small hit in compiletimes, but I think that since it only has to build once (due to caching) this is basically irrelevant.
The important part is the improves user experience that comes from using GTK4.

If possible add a QT backend as well for those who are unfortunate enough to live on a platform without GTK4.

**Comment by mTvare6** [comment]
Does it add more dependencies? That is the more important question
