### ISSUE TITLE
Doesn't use libadwaita

### ISSUE THREAD

**Issue by K4rakara** [mTvare6/hello-world.rs#239]
**Describe the bug**
hello-world.rs is a cutting edge (:rocket:) program, and therefore should be using the best practices(:rocket:) across the board. As such, I would like to recommend that it integrate libadwaita(:rocket:) in order to take advantage of the full power(:rocket:) the GNOME(:rocket:) ecosystem has to offer(:rocket:).

**To Reproduce**
```
cargo build
```

**Expected behavior**
Libadwaita (:rocket:)

**Desktop (please complete the following information):**
 - OS: GNOME OS 42 (:rocket:)
 - Browser: GNOME Web
 - Version: 42, duh (:rocket:)

**Additional context**
GNOME (:rocket:)

**Comment by mTvare6** [comment]
Can you make a PR, and also make sure to build it and check if it adds at least 20 more dependency(if not just inform me of how much it adds)
