### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Birbe** [mTvare6/hello-world.rs#242]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Birbe** [comment]
Please help me. I work at a Fortune 500 company which shall remain unnamed (MasterCard) and we use your crate to run our payment processing sector. This means that you are by law required to help us, for free, with your open-source project that specifies no liability in the LICENSE.

**Comment by booleancoercion** [comment]
This is shocking! How was this left unnoticed until now?

**Comment by leocth** [comment]
:pensive:

**Comment by BAODAU** [comment]
have you tried reinstalling your OS? sometimes it helps

**Comment by Birbe** [comment]
> have you tried reinstalling your OS? sometimes it helps

What is an OS?

**Comment by Birbe** [comment]
Re-opened due to activity

**Comment by mTvare6** [comment]
try removing the battery and putting back it
