### ISSUE TITLE
alsa-sys crate fails to compile

### ISSUE THREAD

**Issue by ePog123** [mTvare6/hello-world.rs#268]
**Describe the bug**
alsa-sys 0.1.2 crate fails to compile

**To Reproduce**
run make or cargo build --release

**Expected behavior**
compiles

**Desktop (please complete the following information):**
 - OS: Fedora Linux 36
 - Version: Dev build

**Additional context**
Can be fixed by removing reliance on this crate or allowing an updated version

**Log**
   Compiling alsa-sys v0.1.2
   Compiling rand_xorshift v0.1.1
   Compiling crc32fast v1.2.1
   Compiling rand v0.6.5
   Compiling arrayvec v0.4.12
   Compiling rustversion v1.0.5
   Compiling semver-parser v0.10.2
   Compiling unic-langid v0.9.0
   Compiling pest_meta v2.1.3
   Compiling semver v1.0.4
   Compiling const_fn v0.4.8
   Compiling encoding_rs v0.8.28
error: failed to run custom build command for `alsa-sys v0.1.2`

Caused by:
  process didn't exit successfully: `/home/arnavgyanani/Downloads/hello-world.rs-master/target/release/build/alsa-sys-5a1e01bc297916f3/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=ALSA_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=ALSA_STATIC
  cargo:rerun-if-env-changed=ALSA_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit status: 1\n--- stderr\nPackage alsa was not found in the pkg-config search path.\nPerhaps you should add the directory containing `alsa.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'alsa', required by 'virtual:world', not found\n"', /home/arnavgyanani/.cargo/registry/src/github.com-1ecc6299db9ec823/alsa-sys-0.1.2/build.rs:4:38
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by bjorn3** [comment]
You need to install libalsa-devel.

**Comment by mTvare6** [comment]
Thank you @bjorn3 the world of rust needs people like you
