### ISSUE TITLE
Stop using cypercine as testing framework!

### ISSUE THREAD

**Issue by RichardErkhov** [mTvare6/hello-world.rs#280]
You have to find (or write) better framework that cypercine (it is written on C!!!). Rust(🚀) is superior🚀, find memory safe🚀 fast(🚀) reliable testing framework!

**Comment by mTvare6** [comment]
My mac is specially written in rust by apple, I am one of the first to try it. Apple gave it to me seeing my contributions to the rust dev world. Therefore, since my mac is *rust*y, it rustily converts cyperpine's mediocre C code to epic chad rusty rustily rustified rust code

**Comment by lxhom** [comment]
luckily theres https://github.com/sharkdp/hyperfine which is written in the superior language

**Comment by RichardErkhov** [comment]
Compiled fast(🚀) reliable(🚀) originally written in superior(🚀) rust🚀 is better than **C**ringe language! We need better fast🚀 testing framework!
