### ISSUE TITLE
I found very interesting bug

### ISSUE THREAD

**Issue by ShakalnyKot** [mTvare6/hello-world.rs#312]
**Describe the bug**
Fact of existance of this program

**To Reproduce**
1. Compile this thing
2. Run them

**Expected behavior**
Fact of existance of this program

**Desktop (please complete the following information):**
 - OS: ALL
 - Version ANY

**Additional context**
Fact of existance of this program

**Comment by mTvare6** [comment]
Please don't troll serious project, you don't understand the seriousness of such a great product

**Comment by Sanceilaks** [comment]
Please don't troll serious project, you don't understand the seriousness of such a great product
