### ISSUE TITLE
Please run cargo fmt

### ISSUE THREAD

**Issue by idanarye** [mTvare6/hello-world.rs#314]
The code is hard to read because it is not properly formatted. Running `cargo fmt` will improve its maintainability.

**Comment by mTvare6** [comment]
This is the best way to format code, its [linus torvalds approved](https://github.com/mTvare6/hello-world.rs/commit/2fb63b273fde7a6b3580f92f76052af872715ee1) and only way to write true trust-worthy tactful talentfulnessisited tangible tantalizing teachable tender thrilling tolerant. cargo fmt is the only part of rust which I discourage and ask people to refrain from using
