### ISSUE TITLE
Won't run on my hamster

### ISSUE THREAD

**Issue by vikramdurai** [mTvare6/hello-world.rs#329]
I thought rust was fast but my hamster was running slowly and now he's showing signs of memory loss. I thought Rust was memory safe??? Plz help

**Comment by Jaimies** [comment]
It should be ok, your hamster is ***safely*** showing signs of memory loss, don't worry!

**Comment by mTvare6** [comment]
Please don't troll serious projects, when I say memory safety, I meant about running it on a cpu and not having memory problems, I don't really know what memory safety is, its just so many people tell it that I use it too*


*: inb someone posts on reddit showing how I don't know the application of memory safety yet I made this project, that part is sarcasm too, to reflect an avg webdev. Now you need not have confusion over interpretation of my words

**Comment by vikramdurai** [comment]
> Please don't troll serious projects, when I say memory safety, I meant about running it on a cpu and not having memory problems, I don't really know what memory safety is, its just so many people tell it that I use it too*
> 
> *: inb someone posts on reddit showing how I don't know the application of memory safety yet I made this project, that part is sarcasm too, to reflect an avg webdev. Now you need not have confusion over interpretation of my words

What trolling?! I am a hapless customer who only wants to figure out WTF is going on with my beloved hamster after he YOUR program. I want to fix it WITHOUT this garbage tech support! My dad works at Microsoft, he will get you fired if I say so!!
