### ISSUE TITLE
Add code to let us use hello-world.rs as an OS

### ISSUE THREAD

**Issue by SkyfallWasTaken** [mTvare6/hello-world.rs#359]
**Is your feature request related to a problem? Please describe.**
It's so depressing when I have to use an OS written in c or c++(🤮) instead of blazing fast, memory safe, lightning quick rust(🚀). Please add the small, tiny, minuscule feature of an operating system to print out "hello world" to the screen. 

**Describe the solution you'd like**
Being able to use blazing fast rust(🚀) based operating system instead of disgusting c/c++ operating system 

**Additional context**
Needs to be blazing fast

**Comment by mTvare6** [comment]
Very true, pls pr, thx
