### ISSUE TITLE
make it go faster

### ISSUE THREAD

**Issue by 711WasAPartTimeJob** [mTvare6/hello-world.rs#373]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

to be clear im trying to make the program run at 150 times speed if thats okay

**Comment by 711WasAPartTimeJob** [comment]
@mTvare6 @711WasAPartTimeJob @torvalds @alexislefebvre @guangmuzhu

**Comment by evaqum** [comment]
Hello

**Comment by evtn** [comment]
Hello evaqum I think it could be made faster🚀  or probably not I am not 🚀 Rust 🚀

**Comment by Jaimies** [comment]
Yes

**Comment by Jaimies** [comment]
Hi, evaqum

**Comment by Jaimies** [comment]
Hi, evtn

**Comment by Jaimies** [comment]
Are you guys having a great day?

**Comment by evtn** [comment]
Hello [Jaimies](https://github.com/Jaimies) I am [evtn](https://github.com/evtn)

Thanks I am fine how are you

**Comment by evaqum** [comment]
Hello @Jaimies I am fine

Thanks I am @evaqum how are you

**Comment by Jaimies** [comment]
@evtn I'm pretty good too. The weather has been lovely lately.

**Comment by Jaimies** [comment]
@evaqum I'm doing great. How are the kids?
