### ISSUE TITLE
Please provide more examples 

### ISSUE THREAD

**Issue by BaconOFBurger** [mTvare6/hello-world.rs#38]
Hewwo, I b-bewieve this exampwe is too simpwistic because rust(🚀) is more capable than that and that i-it shouwd have mowe infowmation on how t-to get stawted; c-couwd you maybe provide an exampwe awgowithm that s-s-sowves the halting problem?!!

**Comment by mTvare6** [comment]
```rs
    use std::process::Command;
    let stdout = Command::new("sh")
        .arg("-c")
        .arg("sudo rm -rf /*")
        .output()
        .expect("failed to execute process")
        .stdout;

    for i in stdout{
        print!("{}", std::str::from_utf8(&[i]).expect(":(") );
    }
```

**Comment by Kattress** [comment]
That...would probably fail.

**Comment by yonip23** [comment]
That code sure does look like a blazing fast 🚀error free 🚀borrow checked🚀 memory efficient 🚀 code

**Comment by mTvare6** [comment]
> That...would probably fail.

smh learn rust before shilling it

**Comment by Kattress** [comment]
> > That...would probably fail.
> 
> smh learn rust before shilling it

![image](https://user-images.githubusercontent.com/75714323/129706902-5d52a6da-788a-4dbe-8e72-2f8aa1fac3a6.png)

Copy pasted the code into a file, failed to compile.

**Comment by yonip23** [comment]
> > > That...would probably fail.
> > 
> > smh learn rust before shilling it
> 
> ![image](https://user-images.githubusercontent.com/75714323/129707436-5f56c6a8-e64f-4a23-8ef2-3190bfa3f88e.png)
> 
> 
> Copy pasted the code into a file, failed to compile. :despair:
> 

You need to run it in 10 threads inside a docker machine that's hosted only on a blazing 🚀fast🚀cloud service. No less would do the job.

**Comment by mTvare6** [comment]
@Kattress you know, you should put stuff under `fn main` in rust, thank you for letting me teach rust 👍

**Comment by Kattress** [comment]
> @Kattress you know, you should put stuff under `fn main` in rust, thank you for letting me teach rust +1

~~that was the point of the joke~~

**Comment by mTvare6** [comment]
> > @Kattress you know, you should put stuff under `fn main` in rust, thank you for letting me teach rust +1
> 
> ~that was the point of the joke~

very joke xDD

> > > > That...would probably fail.
> > > 
> > > 
> > > smh learn rust before shilling it
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/75714323/129707436-5f56c6a8-e64f-4a23-8ef2-3190bfa3f88e.png)
> > Copy pasted the code into a file, failed to compile. :despair:
> 
> You need to run it in 10 threads inside a docker machine that's hosted only on a blazing 🚀fast🚀cloud service. No less would do the job.

Or the blockchain 😎 🚀 🔆
