### ISSUE TITLE
why program so slow :(

### ISSUE THREAD

**Issue by legendofmiracles** [mTvare6/hello-world.rs#41]
With PR https://github.com/mTvare6/hello-world.rs/pull/23 we saw a 10000000% performance increase in prod. Now that the code is gone again, tons of our enterprise level clients are leaving us, due to simple actions taking *decades* to complete. Some smart ass engineer of ours found out that it's now 10000000000000000000000000% slower :((((((((((((((( 
&nbsp;&nbsp;🌎 
🚀 
(transcription: the rocket is flying towards earth)

**Comment by mTvare6** [comment]
Our enterprise customers left because they ran 1 threaded machine and the code required 10 :/

**Comment by legendofmiracles** [comment]
But we can add another 10000000000000000000000000000% by making it multithreaded again, please detect if there are enough cores available and then act accordingly.

Regards

**Comment by mTvare6** [comment]
@legendofmiracles multithreading didn't print hello world apparently, [source: our enterprise customer exorcist365](https://github.com/mTvare6/hello-world.rs/pull/29/commits/0ec3f7293096eb251c67389233ad79df2dfe0419)

**Comment by exorcist365** [comment]
Yes, pr#23 breaks the program so we can't feel the 10000000000000000% performance.

**Comment by Gitleptune** [comment]
I think it's because we need more rust (🚀) crates :(((((

_This issue was written with [basedmark](https://github.com/besterestmark/bettermark)🚀_

**Comment by mTvare6** [comment]
@legendofmiracles memory chadness and blazing basedness and r(ob)ust safety comes at cost of being slow and consuming a lot of cpu and ram, so get used to it
