### ISSUE TITLE
Use the uwuify crate, the fastest text uwuifier in the west

### ISSUE THREAD

**Issue by venand** [mTvare6/hello-world.rs#43]
https://github.com/Daniel-Liu-c0deb0t/uwu

It has over 800 stars so that means it’s great. 

note that this will modify the the output, but with the added advantage of being even more blazingly fast. 
This addresses issue:
https://github.com/mTvare6/hello-world.rs/issues/41

**Comment by mTvare6** [comment]
Added as of latest commit. Not using it though, it would be racial because it only covers english and our enterprise level customers wouldn't want that
