### ISSUE TITLE
suggestion: minimise the program for more speed 🚀

### ISSUE THREAD

**Issue by Gitleptune** [mTvare6/hello-world.rs#49]
Since all the C(ringe) things have made the program be 100000000% not faster I suggest we run the program through a minimising script to make everything faster 🚀!!

_This issue was written with [basedmark](https://github.com/besterestmark/bettermark)🚀_

**Comment by mTvare6** [comment]
What

**Comment by Gitleptune** [comment]
Remove empty lines, comments, etc so the compiler doesn't get confused and is faster (🚀) (not that it isn't already but even fasterer! (🚀))

_This reply was supported by [lantern theme](https://github.com/gitleptune/lantern-theme) 🚀!_

**Comment by mTvare6** [comment]
Make pr smh, I have work
