### ISSUE TITLE
How well does it scale?

### ISSUE THREAD

**Issue by Get-DevVed-YT** [mTvare6/hello-world.rs#54]
Hi, I am a developer at Generic SaaS Startup, and we are using Rust(🚀) to develop our backend because Rust(🚀) is very fast, memory-safe and powerful. We want to use this as a dependency to our backend. However, our backend will need to scale to hundreds of servers and millions of users  once we grow. So, I want to know the scalability metrics of hello-world.rs so we can decide if we should incorporate it in our product, Generic SaaS.

Appreciated,
Generic Name,
Generic SaaS Startup Lead Developer

**Comment by mTvare6** [comment]
Billions of startup already use hello-world.rs in production, you should too! We have tests to ensure we scale upto the solarsystem and can cover the entire universe
![image](https://user-images.githubusercontent.com/57838468/130544434-d332a90e-1d4a-4e9f-be01-df2ec679a3d1.png)

**Comment by mTvare6** [comment]
Its the for the betterment of kids!

**Comment by Get-DevVed-YT** [comment]
I do not understand how it is better for the kids?

**Comment by mTvare6** [comment]
sarcasm 😔

**Comment by mahesh-hegde** [comment]
Dont you see the rocket symbol?

RUST TO THE MOON
