### ISSUE TITLE
Our servers exploded

### ISSUE THREAD

**Issue by Get-DevVed-YT** [mTvare6/hello-world.rs#57]
Hello guys 👋,  it's me, Generic Name, Generic SaaS Startup Lead Developer. 

Recently, we tried to use hello-world.rs as a dependency in our backend. 

When we tried to run it, the servers exploded and our datacenter burnt down.

We lost millions of dollars is damages.
 
Our datacenter has been rebuilt and we added new servers. 

Does anyone have any idea what went wrong? We only tried to spawn one million threads of hello-world.rs, so I don't see what went wrong.

Appreciated,
Generic Name,
Generic SaaS Startup Lead Developer

**Comment by ZaMaZaN4iK** [comment]
> When we tried to run it, the servers exploded and our datacenter burnt down.

Here we don't say "... burnt down", we say "... migrated to the cloud".

**Comment by Get-DevVed-YT** [comment]
We don't use a microservice architecture, we use the monolithic architecture.

**Comment by mTvare6** [comment]
@Get-DevVed-YT did you try rebooting your servers?

**Comment by Gitleptune** [comment]
Yea, same thing happened to me at Generic Comapny:tm: but I tried generic suggestion and it worked perfectly! The power of rust! 🚀
