### ISSUE TITLE
It's 2021, use CMake!

### ISSUE THREAD

**Issue by benthillerkus** [mTvare6/hello-world.rs#59]
I appreciate the effort of creating a solid starting base both for beginners to learn and for advanced programmers to get shit done, but old style make files just do not scale and are actually considered harmful in my organization.
So for us to adopt this, we would require you to rewrite the build system in CMake.

Thank you and btw, the entire department is very excited about using Rust(🚀)

**Comment by overlisted** [comment]
In Meson.

**Comment by mTvare6** [comment]
bruh

**Comment by dar5hak** [comment]
xmake ftw 🚀

**Comment by mTvare6** [comment]
@benthillerkus never unless cmake is written in rust, else its not memory pure and blazing chad :(

**Comment by krupitskas** [comment]
I agree that cmake is very dangerous and not that fast, we need to rewrite it into rust..
