### ISSUE TITLE
COBOL Bindings?

### ISSUE THREAD

**Issue by n1000** [mTvare6/hello-world.rs#65]
Hi, does this hello world rust (🚀) program have COBOL bindings available? I have a large COBOL application (over 40k LOC) that is in the process of being rewritten in rust (🚀🚀).

While this rewrite is ongoing, I would like to slowly oxidize (🚀) some parts of my non-rust (🚀) application. This hello world module looks like a great fit! I have heard great things about how fast (🚀) and light weight (🚀) rust code is! My application is also security critical (🚀) so using rust (🚀) seems like the best option going forward!

**Comment by mTvare6** [comment]
Sorry, no COBOL binds, just write pure rust to be blazing pure and memory chad
