### ISSUE TITLE
Memory usage more than Electron apps

### ISSUE THREAD

**Issue by hirusi** [mTvare6/hello-world.rs#69]
Please fix please!!!

**Comment by mTvare6** [comment]
funny number, also no, rust is blazing fast 😠

**Comment by hirusi** [comment]
why is this closed??? It's literally taking 3 GB on my computer. I can't do anything. :(

**Comment by cravend** [comment]
funny number :)

**Comment by mTvare6** [comment]
@hirusi get more ram, memory fastness and blazing purity comes at a cost

**Comment by Miqueas** [comment]
funny number

**Comment by MacSlash** [comment]
rust :rocket: memory safety comes at a cost sometimes however it is BLAZINGLY :rocket: FAST :rocket: despite the RAM usage

**Comment by mTvare6** [comment]
Flogging the dead horse comment
