### ISSUE TITLE
Possible compile time regression: Why is too blazing fast?

### ISSUE THREAD

**Issue by joseluisq** [mTvare6/hello-world.rs#70]
According to the project's README 🚀

> the compile time is around **2 hours and 30 minutes** on my mac on release mode

I realized that the release build on CI (Linux) takes `20min` which makes this project **too blazing fast 🚀🚀** but not just "blazing fast 🚀".
**This is IMO a clear regression**. 🚀

The problem is that I have no a Mac so I can not reproduce it. 🚀 See possible unrelated issue #41 too 🚀

Here a screenshot that could illustrate why the project compiles **too blazing fast 🚀🚀** on the CI but "blazing fast 🚀" in yours. 🚀

![image](https://user-images.githubusercontent.com/1700322/131847984-edd4631a-ce76-4c28-87d3-7b2c8c024c5b.png)

I assume that your Mac has 1 core (see image above). So your need another Mac with at lest 2 cores or more 🚀 (32 recommended) to match with the multi-core vanguard according [Github Actions **deadly fast 🚀🚀** specs](https://docs.github.com/en/enterprise-server@3.0/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

**Comment by mTvare6** [comment]
my mac has 512 cores btw, but the ci build has 4761 cores
