### ISSUE TITLE
Rewrite the license in Rust

### ISSUE THREAD

**Issue by overlisted** [mTvare6/hello-world.rs#71]
It's really weird that your [license](https://github.com/mTvare6/hello-world.rs/blob/master/LICENSE) is written in [English](https://en.wikipedia.org/wiki/Finnish_language). As one of the best [example](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples) [projects](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards) out there, you should rewrite the [license](https://github.com/mTvare6/hello-world.rs/blob/master/LICENSE) in [Rust](https://www.rust-lang.org/)(   🚀         ) for better [performance](https://www.merriam-webster.com/dictionary/performance)(   🚀         ) and to set a good [example](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples). Here are [some](https://doc.rust-lang.org/std/option/enum.Option.html#variant.Some) benefits of [using](https://en.cppreference.com/w/cpp/keyword/using) [Rust](https://www.rust-lang.org/)(   🚀         ) instead of [any](https://doc.rust-lang.org/std/any/trait.Any.html) other language:
- ## Performance

###### Reliability

# Rust(   🚀         )’s rich type system and ownership model guarantee memory-safety and thread-safety — enabling you to eliminate many classes of bugs at compile-time.
### Rust(   🚀         ) has great documentation, a friendly compiler with useful error messages, and top-notch tooling — an integrated package manager and build tool, smart multi-editor support with auto-completion and type inspections, an auto-formatter, and more.

**Comment by zemlyak** [comment]
rewriting the 🤘  license ©️  in rust 🚀 is a good 🦸‍♂️  idea 💡  considering 🤔  rust's 🚀 memory 🚀 safety 🥽  and ability to do other funny 😃  compiler things 🚀 that i 😊  do not ⏳ know 🤔 about, and being compared 🤔  to english 🇬🇧  which is an interpreted 🤮 language without 😶  a type ⌨️  system 🤣 it looks 👀 much ✨ better 🚀

**Comment by mTvare6** [comment]
@overlisted thanks for abbreviating the README's content, can you make a pr to have the LICENSE rewritten?

**Comment by overlisted** [comment]
@mTvare6 Sure! Although it might take me some time to make my solution perfect.

**Comment by sagudev** [comment]
But the most important thing is that Rust’s rich type system and ownership model guarantee memory-safety and thread-safety — enabling you to eliminate many classes of loopholes in bureaucratic papers (contracts, license, ...) at compile-time.

Rust will also check at compile time that every abstract concept (egg. we, they, customer, program) is properly defined before used.

For demonstration compile time error of GPL 3.0 license:
```
error[E1328]: cannot use term `program` before its definition
 --> src/gpl.rs:16:36
   |
16 |     share and change all versions of a program--to make sure it remains free
   |                                             -- first use appears here
80 |       "The Program" refers to any copyrightable work licensed under this
   |        ^^^^^^^^^^^ definition appears here
```
