### ISSUE TITLE
Generic SaaS has been launched!

### ISSUE THREAD

**Issue by Get-DevVed-YT** [mTvare6/hello-world.rs#79]
Hello guys 👋, it's me, Generic Name, Generic SaaS Startup Lead Developer.

This isn't much of an issue, but I wanted to let you guys know Generic SaaS is finally up! 
 After multiple datacenter fires, we changed our architecture and intertwined a system to work with hello-world.rs, so now we can balance the load of memory between different servers.

Anyway, the link is https://genericsaas.ml/ if you want to check it out. 

Appreciated,
Generic Name,
Generic SaaS Startup Lead Developer

**Comment by mTvare6** [comment]
Woah, very cool, but the font size and colors aren't great

**Comment by Get-DevVed-YT** [comment]
Our designer, Generic Designer, told us people like the font and color. He also said people like using light mode always. So we went with it.

**Comment by Get-DevVed-YT** [comment]
Also, that generic designer is me.

**Comment by mTvare6** [comment]
@Get-DevVed-YT use gruvbox

**Comment by mTvare6** [comment]
@Get-DevVed-YT does https://genericsaas.ml/ use hello-world.rs as backend? If yes please mention it so more people get to know the safety of rust
