### ISSUE TITLE
Dependency count mismatch

### ISSUE THREAD

**Issue by stappersg** [mTvare6/hello-world.rs#80]
Hi,

The  _github summary_ says 1091 dependency. The `README.md` says 1092 dependency.

That mismatch hurts, please make it consistent.

Regards  Stappers

P.S.
I wish project lead success with finding a real challenge.

**Comment by mTvare6** [comment]
@stappersg can you show where it is 1092?

**Comment by mTvare6** [comment]
![image](https://user-images.githubusercontent.com/57838468/132100619-b100a7d7-d7ed-4679-bd46-40bc170f5a0a.png)
