### ISSUE TITLE
Dependency count mismatch

### ISSUE THREAD

**Issue by stappersg** [mTvare6/hello-world.rs#81]
![image](https://user-images.githubusercontent.com/35434094/132107289-2269a110-8697-4cf6-a79f-54926d1c89b0.png)

![image](https://user-images.githubusercontent.com/35434094/132107309-d9865e07-6211-42d7-bebd-c9dafd97df91.png)

Please reopen #80

**Comment by mTvare6** [comment]
It says 1091 for me lol

**Comment by mTvare6** [comment]
Fixed

**Comment by stappersg** [comment]
On Sat, Sep 04, 2021 at 11:23:45PM -0700, mTvare wrote:
> Fixed

Thanks
