### ISSUE TITLE
Rewrite make in Rust 🚀 

### ISSUE THREAD

**Issue by drocha87** [mTvare6/hello-world.rs#85]
I don't see any reason to not rewrite `Makefile` in rust. 🚀 

Makefiles are as old as C and we should not rely in such ancient technology, and off course Makefiles are hard to read and unsafe and dangerous and we should be very scare about it. 🚀

**Comment by mTvare6** [comment]
Stop working on dgit and rewrite `make` in rust :^)

**Comment by mTvare6** [comment]
Just noticed dgit had its last commit 2 years ago
