### ISSUE TITLE
doesn't pass my C compiler, what should I do?

### ISSUE THREAD

**Issue by KnowsCount** [mTvare6/hello-world.rs#92]
should I run it with babel?

**Comment by mTvare6** [comment]
wtf you so unbased, now install rustup which also installs rustdocs, clippy and more stuff to get cargo working

**Comment by boehs** [comment]
> wtf you so unbased, now install rustup which also installs rustdocs, clippy and more stuff to get cargo working

how install with npm 🚀 ?
