### ISSUE TITLE
Commit :ring: messages :speech_balloon: are confusing :confused:

### ISSUE THREAD

**Issue by jagerman** [mTvare6/hello-world.rs#95]
I tried to look :eyes: at the history :books: of this project to help :sos:  myself learn :teacher:  better rust (:rocket:), but I got terribly confused :confused:  by commit messages :speech_balloon: that only consisted of text :abc: but no helpful emoji :smile: .

Could I please :pray: suggest two very important :moneybag: changes to help :sos: potential rust (:rocket:) users?

:one: make sure every message :speech_balloon: has at least :three: emoji in it?

:two: please rewrite :pencil2: the git history :books: entirely so that it is readable :eyes: to ordinary rust (:rocket:) pupils :student:

**Comment by kyx0r** [comment]
Yes, yes! And please, we need more @torvalds coding with rust (🚀). Blazingly fast memroy safety for the kernal with robust rust(🚀) integration! Rewrite as kernal module in rust (🚀), the compiler is git get gud SAFE!

**Comment by mTvare6** [comment]
make a pr which rebases every commit message so far to have emojis

**Comment by neu-ma-tic** [comment]
true
