### ISSUE TITLE
Static executable

### ISSUE THREAD

**Issue by VBGS** [mTvare6/hello-world.rs#98]
Please consider statically linking all dependencies to create a static executable with the musl target.
Maybe you could make it a feature that can be toggled in the Cargo.toml.

**Comment by VBGS** [comment]
It would also be useful in case people want to run hello-world.rs in a docker container with a smaller image.

**Comment by mTvare6** [comment]
@VBGS Please make a PR, I've wasted 369 days of my life on this project and it has been affecting my health, oh and also please pay via BTC to BTC address: 4m0ngU5v3rys0s
